// =============================================
// Free SEO Tools Hub - Multi-Language System
// Updated: Complete 90+ Tools Support (2026)
// =============================================

const translations = {
hi: {
// Navbar
brand: "फ्री SEO टूल्स हब",
home: "होम",
allTools: "सभी टूल्स",
about: "हमारे बारे में",
contact: "संपर्क",
blog: "ब्लॉग",
language: "भाषा",
chooseLang: "🌐 अपनी भाषा चुनें",

// Hero Section
heroHighlight: "फ्री SEO",
heroTools: "टूल्स",
heroSubtitle: "भारत 🇮🇳 और ग्लोबल यूज़र्स 🌍 के लिए",
heroDesc: "90+ फ्री SEO टूल्स भारतीय बिज़नेस, ई-कॉमर्स सेलर्स और ग्लोबल SEO प्रोफेशनल्स के लिए। GST कैलकुलेटर, UPI QR जनरेटर, हिंग्लिश SEO, Amazon FBA कैलकुलेटर, मेटा टैग्स, प्लेजरिज़्म चेकर। सब 100% फ्री, कोई साइनअप नहीं, 2026 अपडेटेड।",
exploreAll: "सभी 90+ टूल्स एक्सप्लोर करें",
browseCat: "कैटेगरी ब्राउज़ करें",

// Quick Links
quickIndia: "🇮🇳 भारत टूल्स",
quickEcom: "🛒 Amazon और ई-कॉमर्स",
quickGlobal: "🌍 ग्लोबल SEO टूल्स",

// Why Choose
whyTitle: "हमारे टूल्स क्यों चुनें?",
whyDesc: "हम भारतीय बिज़नेस, ई-कॉमर्स सेलर्स और ग्लोबल यूज़र्स के लिए 90+ प्रोफेशनल SEO टूल्स देते हैं। हर टूल 100% फ्री और बिना किसी रजिस्ट्रेशन के तुरंत इस्तेमाल करें।",

// Categories
catGlobal: "🌍 ग्लोबल यूनिवर्सल",
catGlobalDesc: "35+ टूल्स। मेटा टैग्स, प्लेजरिज़्म, QR कोड, बैकलिंक।",
catPro: "🚀 एडवांस्ड प्रो",
catProDesc: "18+ प्रोफेशनल टूल्स। SERP, CWV, कंटेंट गैप, लॉग एनालिसिस।",
catPlatform: "🛒 प्लेटफॉर्म टूल्स",
catPlatformDesc: "Amazon SEO, FBA कैलकुलेटर, ई-कॉमर्स टूल्स।",
catIndia: "🇮🇳 भारत स्पेशल",
catIndiaDesc: "GST, UPI, PAN, आधार, उद्यम, हिंग्लिश और 12+ भारतीय भाषा SEO टूल्स।",

// Search
searchPlaceholder: "90+ टूल्स खोजें... (GST, UPI, Amazon, QR, आधार, हिंग्लिश)...",
noToolsFound: "कोई टूल नहीं मिला",
tryDifferent: "दूसरे कीवर्ड से खोजें या नीचे कैटेगरी देखें",

// India Special
indiaBadge: "🇮🇳 भारत स्पेशल",
indiaTitle: "भारतीय यूज़र्स के लिए टूल्स",
indiaDesc: "भारतीय बिज़नेस और यूज़र्स के लिए: GST कैलकुलेटर, UPI QR जनरेटर, PAN वैलिडेटर, उद्यम चेकर, आधार मास्क, हिंग्लिश SEO। भारत के 50 करोड़+ इंटरनेट यूज़र्स के लिए।",
viewAllIndia: "सभी 18+ भारत टूल्स देखें →",

// Platform Tools
platformBadge: "🛒 प्लेटफॉर्म टूल्स",
platformTitle: "Amazon और ई-कॉमर्स SEO",
platformDesc: "सेलर्स और ई-कॉमर्स के लिए: Amazon SEO टूल्स, FBA कैलकुलेटर, प्रोडक्ट रिसर्च।",
viewAllPlatform: "सभी 10+ प्लेटफॉर्म टूल्स देखें →",

// Global SEO
globalBadge: "🌍 ग्लोबल SEO",
globalTitle: "ज़रूरी ग्लोबल SEO टूल्स",
globalDesc: "दुनियाभर के वेबमास्टर्स और SEO प्रोफेशनल्स के लिए। मेटा टैग्स, प्लेजरिज़्म, बैकलिंक एनालिसिस।",
viewAllGlobal: "सभी 35+ ग्लोबल SEO टूल्स देखें →",

// Tool Cards - India
upiTitle: "UPI QR जनरेटर",
upiDesc: "GPay, PhonePe, Paytm के लिए UPI QR कोड बनाएं।",
upiBtn: "UPI QR बनाएं",
gstTitle: "GST कैलकुलेटर",
gstDesc: "CGST, SGST, IGST तुरंत कैलकुलेट करें।",
gstBtn: "GST कैलकुलेट करें",
hinglishTitle: "हिंग्लिश कन्वर्टर",
hinglishDesc: "हिंग्लिश को इंग्लिश कीवर्ड में बदलें। वॉइस सर्च रेडी।",
hinglishBtn: "हिंग्लिश कन्वर्ट करें",
udyamTitle: "उद्यम चेकर",
udyamDesc: "उद्यम रजिस्ट्रेशन वेरिफाई करें। MSME बिज़नेस चेक।",
udyamBtn: "उद्यम चेक करें",
panTitle: "PAN वैलिडेटर",
panDesc: "PAN कार्ड फॉर्मेट वैलिडेट करें। टैक्स कम्प्लायंस टूल।",
panBtn: "PAN वैलिडेट करें",
aadhaarTitle: "आधार मास्क टूल",
aadhaarDesc: "आधार नंबर सुरक्षित छिपाएं। सिर्फ आखिरी 4 अंक दिखाएं।",
aadhaarBtn: "आधार मास्क करें",
socialTitle: "सोशल मीडिया ऑप्टिमाइज़र",
socialDesc: "Facebook, Instagram, Twitter के लिए पोस्ट ऑप्टिमाइज़ करें।",
socialBtn: "पोस्ट ऑप्टिमाइज़ करें",
bhashiniTitle: "भाषिनी SEO",
bhashiniDesc: "12+ भारतीय भाषाओं में SEO। हिंदी, तमिल, तेलुगु और अधिक।",
bhashiniBtn: "भाषिनी SEO",
voiceSearchTitle: "वॉइस सर्च ऑप्टिमाइज़र",
voiceSearchDesc: "Google Voice, Alexa और Siri के लिए कंटेंट ऑप्टिमाइज़ करें।",
voiceSearchBtn: "वॉइस ऑप्टिमाइज़ करें",

// Tool Cards - E-Commerce
amazonSeoTitle: "Amazon SEO टूल फ्री",
amazonSeoDesc: "लाइव डेटा API के साथ कम्प्लीट Amazon ऑप्टिमाइज़ेशन सूट।",
amazonSeoBtn: "Amazon ऑप्टिमाइज़ करें",
fbaTitle: "Amazon FBA कैलकुलेटर",
fbaDesc: "Amazon FBA फीस और प्रॉफिट मार्जिन तुरंत कैलकुलेट करें।",
fbaBtn: "FBA कैलकुलेट करें",
ecomTitle: "ई-कॉमर्स SEO टूल",
ecomDesc: "Shopify, WooCommerce और Magento स्टोर्स ऑप्टिमाइज़ करें।",
ecomBtn: "ई-कॉमर्स SEO",
priceTitle: "प्राइस कम्पेरिज़न टूल",
priceDesc: "Amazon और ई-कॉमर्स प्लेटफॉर्म्स पर प्राइस कम्पेयर करें।",
priceBtn: "प्राइस कम्पेयर करें",

// Tool Cards - Global
metaTitle: "मेटा टैग जनरेटर",
metaDesc: "SEO मेटा टैग्स, Open Graph और Twitter Cards जनरेट करें।",
plagiarismTitle: "प्लेजरिज़्म चेकर",
plagiarismDesc: "कंटेंट ओरिजिनलिटी चेक करें। 80K+ मंथली सर्चेज़।",
qrTitle: "QR कोड जनरेटर",
qrDesc: "URLs, टेक्स्ट, WiFi, vCards के लिए QR कोड बनाएं।",
daTitle: "डोमेन अथॉरिटी चेकर",
daDesc: "DA/PA स्कोर चेक करें। Moz-बेस्ड डोमेन स्ट्रेंथ एनालिसिस।",
backlinkTitle: "बैकलिंक चेकर",
backlinkDesc: "बैकलिंक प्रोफाइल एनालाइज़ करें। कौन आपकी साइट को लिंक कर रहा है।",

// CTA
ctaTitle: "सभी 90+ फ्री SEO टूल्स एक्सप्लोर करने के लिए तैयार?",
ctaDesc: "4 कैटेगरी। 90+ टूल्स। 100% फ्री। कोई साइनअप नहीं। 2026 अपडेटेड।",
browseAll: "सभी कैटेगरी ब्राउज़ करें",

// Footer
footerDesc: "भारतीय यूज़र्स, Amazon और ई-कॉमर्स SEO, और ग्लोबल SEO प्रोफेशनल्स के लिए 90+ फ्री SEO टूल्स। 2024 से 100% फ्री। 2026 अपडेटेड।",
alsoAvailable: "यह भी उपलब्ध:",
quickLinks: "क्विक लिंक्स",
globalToolsFooter: "ग्लोबल SEO",
indiaToolsFooter: "भारत टूल्स",
ecomToolsFooter: "ई-कॉमर्स",
popularTools: "लोकप्रिय टूल्स",
copyright: "© 2026 FreeSEOToolHub.com | सर्वाधिकार सुरक्षित",
privacy: "प्राइवेसी पॉलिसी",
madeIn: "🇮🇳 भारतीय और ग्लोबल SEO समुदाय के लिए बनाया गया | मई 2026 अपडेटेड",

// All Tools Page
allToolsPageTitle: "90+ फ्री SEO टूल्स 2026 | सभी कैटेगरी | FreeSEOToolHub",
allToolsHeader: "🚀 सभी 90+ फ्री SEO टूल्स (2026)",
allToolsHeaderDesc: "4 कैटेगरी में 90+ फ्री SEO टूल्स। भारत स्पेशल, Amazon और ई-कॉमर्स, इंटरनेशनल SEO, प्रोफेशनल SEO टूल्स।",
allToolsSearchPlaceholder: "90+ टूल्स खोजें... (GST, UPI, Amazon, QR, मेटा टैग, प्लेजरिज़्म, बैकलिंक, SERP, कीवर्ड)...",

filterAll: "📋 सभी टूल्स (90+)",
filterGlobal: "🌍 इंटरनेशनल SEO (42)",
filterPro: "🚀 प्रोफेशनल SEO (18)",
filterHot: "🔥 ट्रेंडिंग 2026",

globalCatTitle: "ग्लोबल टूल्स - कोई क्षेत्रीय सीमा नहीं",
globalCatDesc: "दुनियाभर के यूज़र्स के लिए: ये ग्लोबल SEO टूल्स बिना किसी क्षेत्रीय प्रतिबंध के काम करते हैं।",
proBadge: "🚀 प्रोफेशनल SEO टूल्स",
proCatTitle: "एक्सपर्ट्स के लिए एडवांस्ड टूल्स",
proCatDesc: "SEO प्रोफेशनल्स और एजेंसियों के लिए: कम्पेटिटर एनालिसिस, SERP ट्रैकिंग, Core Web Vitals मॉनिटरिंग।",

metaTagTitle: "मेटा टैग जनरेटर",
metaTagDesc: "SEO मेटा टैग्स, Open Graph और Twitter Cards जनरेट करें। 2026 अपडेटेड।",
generateTags: "टैग्स जनरेट करें",
checkNow: "अभी चेक करें",
generateQR: "QR जनरेट करें",
checkDA: "DA चेक करें",
checkBacklinks: "बैकलिंक चेक करें",
findBrokenLinks: "टूटी लिंक ढूंढें",
compressImages: "इमेज कम्प्रेस करें",
checkSSL: "SSL चेक करें",
encodeURL: "URL एनकोड करें",
checkDomain: "डोमेन चेक करें",
generateSchema: "स्कीमा जनरेट करें",
checkGrammar: "ग्रामर चेक करें",
paraphrase: "पैराफ्रेज़ करें",
analyzeHeadline: "हेडलाइन एनालाइज़ करें",
checkDensity: "डेंसिटी चेक करें",
testSpeed: "स्पीड टेस्ट करें",
generateSitemap: "साइटमैप जनरेट करें",
checkRedirects: "रीडायरेक्ट चेक करें",
checkScore: "स्कोर चेक करें",
generateAltText: "Alt टेक्स्ट जनरेट करें",
checkCanonical: "कैनोनिकल चेक करें",
generateHreflang: "Hreflang जनरेट करें",
testResponsive: "रेस्पॉन्सिव टेस्ट करें",
sortCSV: "CSV सॉर्ट करें",
validate: "वैलिडेट करें",
testSchema: "स्कीमा टेस्ट करें",
generateHashtags: "हैशटैग जनरेट करें",

serpFeatureTitle: "SERP फीचर चेकर",
serpFeatureDesc: "SERP फीचर्स एनालाइज़ करें। फीचर्ड स्निपेट्स, PAA, नॉलेज पैनल।",
checkSERP: "SERP चेक करें",
contentGapTitle: "कंटेंट गैप एनालाइज़र",
contentGapDesc: "कम्पेटिटर्स के मुकाबले कंटेंट गैप खोजें।",
findGaps: "गैप खोजें",
cwvTitle: "Core Web Vitals मॉनिटर",
cwvDesc: "LCP, INP, CLS ट्रैक करें। Google रैंकिंग के लिए ज़रूरी।",
monitorCWV: "CWV मॉनिटर करें",
inpTitle: "INP मॉनिटर",
inpDesc: "Interaction to Next Paint मॉनिटरिंग। नया Core Web Vital 2026।",
trackINP: "INP ट्रैक करें",
trafficAnalyzerTitle: "ट्रैफिक एनालाइज़र",
trafficAnalyzerDesc: "वेबसाइट ट्रैफिक एनालाइज़ करें।",
analyzeTraffic: "ट्रैफिक एनालाइज़ करें",
competitorSerpTitle: "कम्पेटिटर SERP एनालाइज़र",
competitorSerpDesc: "टॉप 10 रैंकिंग पेजेज़ एनालाइज़ करें।",
analyzeCompetitors: "कम्पेटिटर्स एनालाइज़ करें",
gscVisualizerTitle: "GSC डेटा विज़ुअलाइज़र",
gscVisualizerDesc: "Google Search Console डेटा को इंटरैक्टिव चार्ट्स में देखें।",
visualizeGSC: "GSC विज़ुअलाइज़ करें",
keywordDifficultyTitle: "कीवर्ड डिफिकल्टी चेकर",
keywordDifficultyDesc: "रैंकिंग डिफिकल्टी चेक करें। आसान कीवर्ड खोजें।",
checkDifficulty: "डिफिकल्टी चेक करें",
keywordGapTitle: "कीवर्ड गैप एनालाइज़र",
keywordGapDesc: "कम्पेटिटर्स से कीवर्ड कम्पेयर करें।",
compareKeywords: "कीवर्ड कम्पेयर करें",
serpFeaturesTitle: "SERP फीचर्स एनालाइज़र",
serpFeaturesDesc: "किसी भी कीवर्ड के लिए डिटेल्ड SERP फीचर एनालिसिस।",
analyzeSERP: "SERP एनालाइज़ करें",
serpVolatilityTitle: "SERP वोलैटिलिटी चेकर",
serpVolatilityDesc: "SERP बदलाव ट्रैक करें। Google एल्गोरिदम अपडेट डिटेक्ट करें।",
checkVolatility: "वोलैटिलिटी चेक करें",
logAnalyzerTitle: "लॉग एनालाइज़र",
logAnalyzerDesc: "सर्वर लॉग एनालाइज़ करें। Googlebot क्रॉल बिहेवियर समझें।",
analyzeLogs: "लॉग एनालाइज़ करें",
internalLinkTitle: "इंटरनल लिंक सजेस्टर",
internalLinkDesc: "SEO के लिए स्मार्ट इंटरनल लिंकिंग सुझाव।",
getSuggestions: "सुझाव लें",
sovTitle: "शेयर ऑफ वॉइस कैलकुलेटर",
sovDesc: "सर्च में ब्रांड विज़िबिलिटी कैलकुलेट करें।",
calculateSOV: "SOV कैलकुलेट करें",
marketSaturationTitle: "मार्केट सैचुरेशन चेकर",
marketSaturationDesc: "किसी भी नीश की मार्केट सैचुरेशन चेक करें।",
checkMarket: "मार्केट चेक करें",
mobileDesktopTitle: "मोबाइल डेस्कटॉप रैंक ट्रैकर",
mobileDesktopDesc: "मोबाइल vs डेस्कटॉप रैंकिंग कम्पेयर करें।",
trackRanks: "रैंक ट्रैक करें",

brokenLinkTitle: "टूटी लिंक चेकर",
brokenLinkDesc: "किसी भी वेबसाइट पर 404 एरर्स और डेड लिंक खोजें।",
imageCompressTitle: "इमेज कम्प्रेसर",
imageCompressDesc: "JPG, PNG, WebP इमेज कम्प्रेस करें। साइज़ घटाएं, क्वालिटी रखें।",
sslTitle: "SSL चेकर",
sslDesc: "SSL सर्टिफिकेट वैधता और एक्सपायरी डेट चेक करें।",
urlEncoderTitle: "URL एनकोडर/डिकोडर",
urlEncoderDesc: "URLs एनकोड और डिकोड करें। डेवलपर्स के लिए ज़रूरी टूल।",
domainCheckTitle: "डोमेन चेकर",
domainCheckDesc: "डोमेन अवेलेबिलिटी और रजिस्ट्रेशन डिटेल्स चेक करें।",
schemaTitle: "स्कीमा मार्कअप जनरेटर",
schemaDesc: "रिच स्निपेट्स के लिए JSON-LD स्ट्रक्चर्ड डेटा बनाएं।",
grammarTitle: "ग्रामर और स्पेल चेकर",
grammarDesc: "ग्रामर, स्पेलिंग और पंक्चुएशन एरर्स चेक करें।",
paraphraseTitle: "पैराफ्रेज़िंग टूल",
paraphraseDesc: "AI से कंटेंट रीराइट करें। प्लेजरिज़्म से बचें, रीडेबिलिटी बढ़ाएं।",
headlineTitle: "हेडिंग हेडलाइन एनालाइज़र",
headlineDesc: "अपनी हेडलाइन्स स्कोर करें। बेहतर टाइटल्स से CTR बढ़ाएं।",
keywordDensityTitle: "कीवर्ड डेंसिटी चेकर",
keywordDensityDesc: "किसी भी पेज पर कीवर्ड डेंसिटी और फ्रीक्वेंसी एनालाइज़ करें।",
speedTestTitle: "वेबसाइट स्पीड टेस्ट",
speedTestDesc: "पेज लोड टाइम और परफॉरमेंस मेट्रिक्स टेस्ट करें।",
sitemapTitle: "XML साइटमैप जनरेटर",
sitemapDesc: "बेहतर इंडेक्सिंग के लिए XML साइटमैप जनरेट करें।",
redirectTitle: "रीडायरेक्ट चेन चेकर",
redirectDesc: "रीडायरेक्ट चेन और लूप खोजें। SEO इश्यू फिक्स करें।",
readabilityTitle: "रीडेबिलिटी स्कोर चेकर",
readabilityDesc: "Flesch-Kincaid रीडिंग ईज़। कंटेंट रीडेबिलिटी सुधारें।",
altGeneratorTitle: "इमेज Alt जनरेटर",
altGeneratorDesc: "इमेज के लिए SEO-फ्रेंडली alt टेक्स्ट जनरेट करें।",
canonicalTitle: "कैनोनिकल URL चेकर",
canonicalDesc: "कैनोनिकल टैग्स चेक करें। डुप्लीकेट कंटेंट इश्यू से बचें।",
hreflangTitle: "Hreflang जनरेटर",
hreflangDesc: "मल्टीलिंगुअल साइट्स के लिए hreflang टैग्स जनरेट करें।",
responsiveTitle: "रेस्पॉन्सिव टेस्टर",
responsiveDesc: "अलग-अलग स्क्रीन साइज़ पर वेबसाइट टेस्ट करें।",
csvSorterTitle: "CSV सॉर्टर",
csvSorterDesc: "CSV फाइल्स को ऑनलाइन सॉर्ट, फिल्टर और ऑर्गनाइज़ करें।",
headingStructureTitle: "हेडिंग स्ट्रक्चर वैलिडेटर",
headingStructureDesc: "SEO के लिए H1-H6 हेडिंग हायरार्की वैलिडेट करें।",
schemaTesterTitle: "स्कीमा स्ट्रक्चर्ड डेटा टेस्टर",
schemaTesterDesc: "स्कीमा मार्कअप कोड टेस्ट और वैलिडेट करें।",
hashtagTitle: "हैशटैग जनरेटर",
hashtagDesc: "सोशल मीडिया के लिए ट्रेंडिंग हैशटैग जनरेट करें।",
totalCountBadge: "90+ फ्री SEO टूल्स | 4 कैटेगरी | 100% फ्री | कोई साइनअप नहीं | 2026 अपडेटेड",
madeFor: "🇮🇳 ग्लोबल SEO समुदाय के लिए बनाया गया | 2026 अपडेटेड",

// New India Tools
voiceKeywordsTitle: "वॉइस सर्च कीवर्ड्स",
voiceKeywordsDesc: "भारतीय भाषाओं के लिए वॉइस सर्च कीवर्ड खोजें।",
voiceQuestionTitle: "वॉइस क्वेश्चन जनरेटर",
voiceQuestionDesc: "क्वेश्चन-बेस्ड वॉइस सर्च क्वेरीज़ जनरेट करें।",
hinglishVolumeTitle: "हिंग्लिश वॉल्यूम एस्टीमेटर",
hinglishVolumeDesc: "हिंग्लिश कीवर्ड्स का सर्च वॉल्यूम एस्टीमेट करें।",
trendingKeywordsTitle: "ट्रेंडिंग कीवर्ड्स फाइंडर",
trendingKeywordsDesc: "भारतीय मार्केट के लिए ट्रेंडिंग कीवर्ड खोजें।",
festivalTitle: "फेस्टिवल कीवर्ड कैलेंडर",
festivalDesc: "भारत के लिए फेस्टिवल-बेस्ड कीवर्ड प्लानिंग।",
regionalTitle: "रीजनल कीवर्ड्स इंडिया",
regionalDesc: "भारतीय राज्यों के लिए रीजनल भाषा कीवर्ड खोजें।",
cityKeywordsTitle: "इंडियन सिटी कीवर्ड्स",
cityKeywordsDesc: "भारतीय शहरों के लिए सिटी-वाइज़ कीवर्ड रिसर्च।",
lowCompetitionTitle: "लो कम्पीटीशन कीवर्ड्स",
lowCompetitionDesc: "भारतीय मार्केट के लिए कम कम्पीटीशन वाले कीवर्ड खोजें।",

// New E-Commerce Tools
amazonProductTitle: "Amazon प्रोडक्ट रिसर्च",
amazonProductDesc: "Amazon सेलिंग के लिए प्रॉफिटेबल प्रोडक्ट रिसर्च करें।",
amazonApiTitle: "Amazon SEO टूल API",
amazonApiDesc: "Amazon SEO डेटा और ऑटोमेशन के लिए API एक्सेस।",
profitMarginTitle: "प्रॉफिट मार्जिन कैलकुलेटर",
profitMarginDesc: "ई-कॉमर्स प्रोडक्ट्स का प्रॉफिट मार्जिन कैलकुलेट करें।",

// New Global Tools
trendsVisualizerTitle: "Google Trends विज़ुअलाइज़र",
trendsVisualizerDesc: "Google Trends डेटा को चार्ट्स के साथ विज़ुअलाइज़ करें।",
trendDiscoveryTitle: "ट्रेंड डिस्कवरी",
trendDiscoveryDesc: "ट्रेंडिंग टॉपिक्स और कीवर्ड डिस्कवर करें।",
aiDetectorTitle: "AI कंटेंट डिटेक्टर",
aiDetectorDesc: "AI-जनरेटेड कंटेंट डिटेक्ट करें। ChatGPT, Bard डिटेक्शन।",
aiIdeasTitle: "AI आइडियाज़ जनरेटर",
aiIdeasDesc: "AI का उपयोग करके कंटेंट आइडियाज़ जनरेट करें।",
aiVisibilityTitle: "AI विज़िबिलिटी ट्रैकर",
aiVisibilityDesc: "अपना AI सर्च विज़िबिलिटी स्कोर ट्रैक करें।",
contentOriginalityTitle: "कंटेंट ओरिजिनलिटी चेकर",
contentOriginalityDesc: "चेक करें कि आपका कंटेंट 100% ओरिजिनल है या नहीं।",
longTailTitle: "लॉन्ग टेल कीवर्ड जनरेटर",
longTailDesc: "लॉन्ग-टेल कीवर्ड आइडियाज़ जनरेट करें।",
questionKeywordTitle: "क्वेश्चन कीवर्ड जनरेटर",
questionKeywordDesc: "सीड कीवर्ड से क्वेश्चन-बेस्ड कीवर्ड जनरेट करें।",
crawlerTitle: "वेबसाइट क्रॉलर",
crawlerDesc: "किसी भी वेबसाइट को क्रॉल करें। सभी पेज और SEO इश्यू खोजें।",
pagespeedTitle: "PageSpeed Insights",
pagespeedDesc: "Google PageSpeed Insights एनालिसिस टूल।",
yoastTitle: "Yoast एनालाइज़र",
yoastDesc: "Yoast SEO प्लगइन की तरह कंटेंट एनालाइज़ करें।",
youtubeTitle: "YouTube SEO टूल्स",
youtubeDesc: "बेहतर रैंकिंग के लिए YouTube वीडियो ऑप्टिमाइज़ करें।",
seoNewsTitle: "SEO न्यूज़",
seoNewsDesc: "लेटेस्ट SEO न्यूज़ और Google एल्गोरिदम अपडेट्स।",
googleVerifyTitle: "Google साइट वेरिफिकेशन",
googleVerifyDesc: "Google साइट वेरिफिकेशन मेटा टैग जनरेट करें।",
multilingualTitle: "मल्टीलिंगुअल SEO",
multilingualDesc: "मल्टीलिंगुअल वेबसाइट्स के लिए SEO ऑप्टिमाइज़ेशन।",

// New Pro/Local SEO Tools
localChecklistTitle: "लोकल SEO चेकलिस्ट",
localChecklistDesc: "कम्प्लीट लोकल SEO ऑप्टिमाइज़ेशन चेकलिस्ट।",
localRankTitle: "लोकल रैंक ट्रैकर",
localRankDesc: "अपने बिज़नेस की लोकल SEO रैंकिंग ट्रैक करें।",
localCompetitorTitle: "लोकल कम्पेटिटर मॉनिटर",
localCompetitorDesc: "लोकल कम्पेटिटर्स की SEO स्ट्रैटेजी मॉनिटर करें।",
localListingTitle: "लोकल लिस्टिंग चेकर",
localListingDesc: "प्लेटफॉर्म्स पर अपनी लोकल बिज़नेस लिस्टिंग चेक करें।",
cityWiseKeywordsTitle: "सिटी वाइज़ कीवर्ड्स",
cityWiseKeywordsDesc: "शहर के नाम से लोकल कीवर्ड रिसर्च करें।",
advancedPincodeTitle: "एडवांस्ड पिनकोड फाइंडर",
advancedPincodeDesc: "एडवांस्ड पिनकोड और लोकेशन फाइंडर टूल।",
geoOptimizerTitle: "जियो ऑप्टिमाइज़र",
geoOptimizerDesc: "लोकेशन-बेस्ड SEO के लिए कंटेंट ऑप्टिमाइज़ करें।",
geoAnalyticsTitle: "जियो एनालिटिक्स",
geoAnalyticsDesc: "लोकेशन-बेस्ड SEO परफॉरमेंस एनालिटिक्स।"
},

ur: {
brand: "مفت SEO ٹولز ہب",
home: "ہوم",
allTools: "تمام ٹولز",
about: "ہمارے بارے میں",
contact: "رابطہ",
blog: "بلاگ",
language: "زبان",
chooseLang: "🌐 اپنی زبان منتخب کریں",

heroHighlight: "مفت SEO",
heroTools: "ٹولز",
heroSubtitle: "بھارت 🇮🇳 اور عالمی صارفین 🌍 کے لیے",
heroDesc: "بھارتی کاروبار، ای کامرس سیلرز اور عالمی SEO پروفیشنلز کے لیے 90+ مفت SEO ٹولز۔ GST کیلکولیٹر، UPI QR جنریٹر، ہنگلش SEO، Amazon FBA کیلکولیٹر۔",
exploreAll: "تمام 90+ ٹولز دریافت کریں",
browseCat: "کیٹگریز براؤز کریں",

quickIndia: "🇮🇳 بھارت ٹولز",
quickEcom: "🛒 Amazon اور ای کامرس",
quickGlobal: "🌍 عالمی SEO ٹولز",

whyTitle: "ہمارے ٹولز کیوں منتخب کریں؟",
whyDesc: "ہم بھارتی کاروبار، ای کامرس سیلرز اور عالمی صارفین کے لیے 90+ پروفیشنل SEO ٹولز فراہم کرتے ہیں۔",

catGlobal: "🌍 عالمی یونیورسل",
catGlobalDesc: "35+ ٹولز۔ میٹا ٹیگز، پلیجرزم، QR کوڈ، بیک لنک۔",
catPro: "🚀 ایڈوانسڈ پرو",
catProDesc: "18+ پروفیشنل ٹولز۔ SERP، CWV، کنٹینٹ گیپ۔",
catPlatform: "🛒 پلیٹ فارم ٹولز",
catPlatformDesc: "Amazon SEO، FBA کیلکولیٹر، ای کامرس ٹولز۔",
catIndia: "🇮🇳 بھارت اسپیشل",
catIndiaDesc: "GST، UPI، PAN، آدھار، ادیم، ہنگلش SEO۔",

searchPlaceholder: "90+ ٹولز تلاش کریں...",
noToolsFound: "کوئی ٹول نہیں ملا",
tryDifferent: "دوسرے الفاظ سے تلاش کریں",

indiaBadge: "🇮🇳 بھارت اسپیشل",
indiaTitle: "بھارتی صارفین کے لیے ٹولز",
indiaDesc: "بھارتی کاروبار کے لیے: GST، UPI QR، PAN، آدھار، ادیم، ہنگلش SEO۔",
viewAllIndia: "تمام 18+ بھارت ٹولز دیکھیں →",

platformBadge: "🛒 پلیٹ فارم ٹولز",
platformTitle: "Amazon اور ای کامرس SEO",
platformDesc: "سیلرز کے لیے: Amazon SEO، FBA کیلکولیٹر، پروڈکٹ ریسرچ۔",
viewAllPlatform: "تمام 10+ پلیٹ فارم ٹولز دیکھیں →",

globalBadge: "🌍 عالمی SEO",
globalTitle: "ضروری عالمی SEO ٹولز",
globalDesc: "دنیا بھر کے ویب ماسٹرز کے لیے۔ میٹا ٹیگز، پلیجرزم، بیک لنک تجزیہ۔",
viewAllGlobal: "تمام 35+ عالمی SEO ٹولز دیکھیں →",

upiTitle: "UPI QR جنریٹر",
upiDesc: "GPay، PhonePe، Paytm کے لیے UPI QR کوڈ بنائیں۔",
upiBtn: "UPI QR بنائیں",
gstTitle: "GST کیلکولیٹر",
gstDesc: "CGST، SGST، IGST فوری کیلکولیٹ کریں۔",
gstBtn: "GST کیلکولیٹ کریں",
hinglishTitle: "ہنگلش کنورٹر",
hinglishDesc: "ہنگلش کو انگلش کیورڈز میں تبدیل کریں۔",
hinglishBtn: "ہنگلش کنورٹ کریں",
udyamTitle: "ادیم چیکر",
udyamDesc: "ادیم رجسٹریشن کی تصدیق کریں۔",
udyamBtn: "ادیم چیک کریں",
panTitle: "PAN ویلڈیٹر",
panDesc: "PAN کارڈ فارمیٹ ویلڈیٹ کریں۔",
panBtn: "PAN ویلڈیٹ کریں",
aadhaarTitle: "آدھار ماسک ٹول",
aadhaarDesc: "آدھار نمبر محفوظ طریقے سے چھپائیں۔",
aadhaarBtn: "آدھار ماسک کریں",
socialTitle: "سوشل میڈیا آپٹیمائزر",
socialDesc: "Facebook، Instagram، Twitter کے لیے پوسٹ آپٹیمائز کریں۔",
socialBtn: "پوسٹ آپٹیمائز کریں",
bhashiniTitle: "بھاشنی SEO",
bhashiniDesc: "12+ بھارتی زبانوں میں SEO۔",
bhashiniBtn: "بھاشنی SEO",
voiceSearchTitle: "وائس سرچ آپٹیمائزر",
voiceSearchDesc: "Google Voice، Alexa اور Siri کے لیے مواد آپٹیمائز کریں۔",
voiceSearchBtn: "وائس آپٹیمائز کریں",

amazonSeoTitle: "Amazon SEO ٹول فری",
amazonSeoDesc: "لائیو ڈیٹا API کے ساتھ Amazon آپٹیمائزیشن۔",
amazonSeoBtn: "Amazon آپٹیمائز کریں",
fbaTitle: "Amazon FBA کیلکولیٹر",
fbaDesc: "Amazon FBA فیس اور منافع فوری کیلکولیٹ کریں۔",
fbaBtn: "FBA کیلکولیٹ کریں",
ecomTitle: "ای کامرس SEO ٹول",
ecomDesc: "Shopify، WooCommerce اسٹورز آپٹیمائز کریں۔",
ecomBtn: "ای کامرس SEO",
priceTitle: "قیمت موازنہ ٹول",
priceDesc: "Amazon پر قیمتوں کا موازنہ کریں۔",
priceBtn: "قیمت موازنہ کریں",

metaTitle: "میٹا ٹیگ جنریٹر",
metaDesc: "SEO میٹا ٹیگز، Open Graph اور Twitter Cards بنائیں۔",
plagiarismTitle: "پلیجرزم چیکر",
plagiarismDesc: "مواد کی اصلیت چیک کریں۔ 80K+ ماہانہ تلاش۔",
qrTitle: "QR کوڈ جنریٹر",
qrDesc: "URLs، ٹیکسٹ، WiFi کے لیے QR کوڈ بنائیں۔",
daTitle: "ڈومین اتھارٹی چیکر",
daDesc: "DA/PA اسکور چیک کریں۔",
backlinkTitle: "بیک لنک چیکر",
backlinkDesc: "بیک لنک پروفائل کا تجزیہ کریں۔",

ctaTitle: "تمام 90+ مفت SEO ٹولز دریافت کریں",
ctaDesc: "4 کیٹگریز۔ 90+ ٹولز۔ 100% مفت۔ 2026 اپڈیٹڈ۔",
browseAll: "تمام کیٹگریز براؤز کریں",

footerDesc: "بھارتی صارفین اور عالمی SEO کمیونٹی کے لیے 90+ مفت SEO ٹولز۔",
alsoAvailable: "یہ بھی دستیاب:",
quickLinks: "فوری لنکس",
globalToolsFooter: "عالمی SEO",
indiaToolsFooter: "بھارت ٹولز",
ecomToolsFooter: "ای کامرس",
popularTools: "مقبول ٹولز",
copyright: "© 2026 FreeSEOToolHub.com | جملہ حقوق محفوظ",
privacy: "پرائیویسی پالیسی",
madeIn: "🇮🇳 بھارتی اور عالمی SEO کمیونٹی کے لیے | 2026 اپڈیٹڈ",

allToolsPageTitle: "90+ مفت SEO ٹولز 2026 | تمام کیٹگریز",
allToolsHeader: "🚀 تمام 90+ مفت SEO ٹولز (2026)",
allToolsHeaderDesc: "4 کیٹگریز میں 90+ مفت SEO ٹولز۔",
allToolsSearchPlaceholder: "90+ ٹولز تلاش کریں...",

filterAll: "📋 تمام ٹولز (90+)",
filterGlobal: "🌍 عالمی SEO (42)",
filterPro: "🚀 پروفیشنل SEO (18)",
filterHot: "🔥 ٹرینڈنگ 2026",

globalCatTitle: "عالمی ٹولز - کوئی علاقائی حد نہیں",
globalCatDesc: "دنیا بھر کے صارفین کے لیے۔",
proBadge: "🚀 پروفیشنل SEO ٹولز",
proCatTitle: "ماہرین کے لیے ایڈوانسڈ ٹولز",
proCatDesc: "SEO پروفیشنلز اور ایجنسیوں کے لیے۔",

metaTagTitle: "میٹا ٹیگ جنریٹر",
metaTagDesc: "SEO میٹا ٹیگز جنریٹ کریں۔ 2026 اپڈیٹڈ۔",
generateTags: "ٹیگز بنائیں",
checkNow: "ابھی چیک کریں",
generateQR: "QR بنائیں",
checkDA: "DA چیک کریں",
checkBacklinks: "بیک لنک چیک کریں",
findBrokenLinks: "ٹوٹی لنکس ڈھونڈیں",
compressImages: "تصاویر کمپریس کریں",
checkSSL: "SSL چیک کریں",
encodeURL: "URL انکوڈ کریں",
checkDomain: "ڈومین چیک کریں",
generateSchema: "اسکیما بنائیں",
checkGrammar: "گرامر چیک کریں",
paraphrase: "پیرافریز کریں",
analyzeHeadline: "ہیڈلائن تجزیہ کریں",
checkDensity: "کثافت چیک کریں",
testSpeed: "سپیڈ ٹیسٹ کریں",
generateSitemap: "سائٹ میپ بنائیں",
checkRedirects: "ری ڈائریکٹ چیک کریں",
checkScore: "اسکور چیک کریں",
generateAltText: "Alt ٹیکسٹ بنائیں",
checkCanonical: "کینونیکل چیک کریں",
generateHreflang: "Hreflang بنائیں",
testResponsive: "ریسپانسیو ٹیسٹ کریں",
sortCSV: "CSV ترتیب دیں",
validate: "تصدیق کریں",
testSchema: "اسکیما ٹیسٹ کریں",
generateHashtags: "ہیش ٹیگ بنائیں",

serpFeatureTitle: "SERP فیچر چیکر",
serpFeatureDesc: "SERP فیچرز کا تجزیہ کریں۔",
checkSERP: "SERP چیک کریں",
contentGapTitle: "کنٹینٹ گیپ اینالائزر",
contentGapDesc: "مقابلوں کے مقابلے میں گیپ ڈھونڈیں۔",
findGaps: "گیپ ڈھونڈیں",
cwvTitle: "Core Web Vitals مانیٹر",
cwvDesc: "LCP، INP، CLS ٹریک کریں۔",
monitorCWV: "CWV مانیٹر کریں",
inpTitle: "INP مانیٹر",
inpDesc: "Interaction to Next Paint مانیٹرنگ۔",
trackINP: "INP ٹریک کریں",
trafficAnalyzerTitle: "ٹریفک اینالائزر",
trafficAnalyzerDesc: "ویب سائٹ ٹریفک کا تجزیہ کریں۔",
analyzeTraffic: "ٹریفک تجزیہ کریں",
competitorSerpTitle: "مقابل SERP اینالائزر",
competitorSerpDesc: "ٹاپ 10 رینکنگ پیجز کا تجزیہ کریں۔",
analyzeCompetitors: "مقابلوں کا تجزیہ کریں",
gscVisualizerTitle: "GSC ڈیٹا ویژولائزر",
gscVisualizerDesc: "Google Search Console ڈیٹا دیکھیں۔",
visualizeGSC: "GSC دیکھیں",
keywordDifficultyTitle: "کیورڈ ڈیفکلٹی چیکر",
keywordDifficultyDesc: "رینکنگ ڈیفکلٹی چیک کریں۔",
checkDifficulty: "ڈیفکلٹی چیک کریں",
keywordGapTitle: "کیورڈ گیپ اینالائزر",
keywordGapDesc: "مقابلوں سے کیورڈز موازنہ کریں۔",
compareKeywords: "کیورڈز موازنہ کریں",
serpFeaturesTitle: "SERP فیچرز اینالائزر",
serpFeaturesDesc: "کسی بھی کیورڈ کا SERP تجزیہ۔",
analyzeSERP: "SERP تجزیہ کریں",
serpVolatilityTitle: "SERP وولیٹیلیٹی چیکر",
serpVolatilityDesc: "SERP تبدیلیاں ٹریک کریں۔",
checkVolatility: "وولیٹیلیٹی چیک کریں",
logAnalyzerTitle: "لاگ اینالائزر",
logAnalyzerDesc: "سرور لاگ کا تجزیہ کریں۔",
analyzeLogs: "لاگ تجزیہ کریں",
internalLinkTitle: "انٹرنل لنک سجیسٹر",
internalLinkDesc: "SEO کے لیے سمارٹ انٹرنل لنکنگ۔",
getSuggestions: "تجاویز لیں",
sovTitle: "شیئر آف وائس کیلکولیٹر",
sovDesc: "برانڈ ویزیبیلٹی کیلکولیٹ کریں۔",
calculateSOV: "SOV کیلکولیٹ کریں",
marketSaturationTitle: "مارکیٹ سیچوریشن چیکر",
marketSaturationDesc: "کسی بھی نیش کی مارکیٹ چیک کریں۔",
checkMarket: "مارکیٹ چیک کریں",
mobileDesktopTitle: "موبائل ڈیسک ٹاپ رینک ٹریکر",
mobileDesktopDesc: "موبائل vs ڈیسک ٹاپ رینکنگ موازنہ۔",
trackRanks: "رینک ٹریک کریں",

brokenLinkTitle: "ٹوٹی لنک چیکر",
brokenLinkDesc: "ویب سائٹ پر 404 ایررز ڈھونڈیں۔",
imageCompressTitle: "تصویر کمپریسر",
imageCompressDesc: "JPG، PNG، WebP تصاویر کمپریس کریں۔",
sslTitle: "SSL چیکر",
sslDesc: "SSL سرٹیفکیٹ کی میعاد چیک کریں۔",
urlEncoderTitle: "URL انکوڈر/ڈیکوڈر",
urlEncoderDesc: "URLs انکوڈ اور ڈیکوڈ کریں۔",
domainCheckTitle: "ڈومین چیکر",
domainCheckDesc: "ڈومین کی دستیابی چیک کریں۔",
schemaTitle: "اسکیما مارک اپ جنریٹر",
schemaDesc: "رچ سنیپٹس کے لیے JSON-LD ڈیٹا بنائیں۔",
grammarTitle: "گرامر اور سپیل چیکر",
grammarDesc: "گرامر، سپیلنگ کی غلطیاں چیک کریں۔",
paraphraseTitle: "پیرافریزنگ ٹول",
paraphraseDesc: "AI سے مواد دوبارہ لکھیں۔",
headlineTitle: "ہیڈنگ ہیڈلائن اینالائزر",
headlineDesc: "اپنی ہیڈلائنز اسکور کریں۔",
keywordDensityTitle: "کیورڈ ڈینسٹی چیکر",
keywordDensityDesc: "کیورڈ ڈینسٹی کا تجزیہ کریں۔",
speedTestTitle: "ویب سائٹ سپیڈ ٹیسٹ",
speedTestDesc: "پیج لوڈ ٹائم ٹیسٹ کریں۔",
sitemapTitle: "XML سائٹ میپ جنریٹر",
sitemapDesc: "بہتر انڈیکسنگ کے لیے سائٹ میپ بنائیں۔",
redirectTitle: "ری ڈائریکٹ چین چیکر",
redirectDesc: "ری ڈائریکٹ چین ڈھونڈیں۔",
readabilityTitle: "ریڈیبیلیٹی اسکور چیکر",
readabilityDesc: "Flesch-Kincaid ریڈنگ ایز۔",
altGeneratorTitle: "تصویر Alt جنریٹر",
altGeneratorDesc: "SEO فرینڈلی alt ٹیکسٹ بنائیں۔",
canonicalTitle: "کینونیکل URL چیکر",
canonicalDesc: "کینونیکل ٹیگز چیک کریں۔",
hreflangTitle: "Hreflang جنریٹر",
hreflangDesc: "ملٹی لینگوئل سائٹس کے لیے hreflang ٹیگز۔",
responsiveTitle: "ریسپانسیو ٹیسٹر",
responsiveDesc: "مختلف اسکرین سائز پر ٹیسٹ کریں۔",
csvSorterTitle: "CSV سارٹر",
csvSorterDesc: "CSV فائلیں آن لائن ترتیب دیں۔",
headingStructureTitle: "ہیڈنگ اسٹرکچر ویلڈیٹر",
headingStructureDesc: "H1-H6 ہیڈنگ ہائراکی ویلڈیٹ کریں۔",
schemaTesterTitle: "اسکیما ڈیٹا ٹیسٹر",
schemaTesterDesc: "اسکیما مارک اپ ٹیسٹ کریں۔",
hashtagTitle: "ہیش ٹیگ جنریٹر",
hashtagDesc: "سوشل میڈیا کے لیے ہیش ٹیگ بنائیں۔",
totalCountBadge: "90+ مفت SEO ٹولز | 4 کیٹگریز | 100% مفت | 2026 اپڈیٹڈ",
madeFor: "🇮🇳 عالمی SEO کمیونٹی کے لیے | 2026 اپڈیٹڈ"
},

de: {
brand: "Kostenlose SEO-Tools Hub",
home: "Startseite",
allTools: "Alle Tools",
about: "Über uns",
contact: "Kontakt",
blog: "Blog",
language: "Sprache",
chooseLang: "🌐 Wählen Sie Ihre Sprache",

heroHighlight: "Kostenlose SEO",
heroTools: "Tools",
heroSubtitle: "Für globale Nutzer 🌍",
heroDesc: "90+ kostenlose SEO-Tools. Meta-Tags, Plagiatsprüfung, QR-Codes, Backlinks. 100% kostenlos, keine Anmeldung.",
exploreAll: "Alle 90+ Tools erkunden",
browseCat: "Kategorien durchsuchen",

quickIndia: "🇮🇳 Indien Tools",
quickEcom: "🛒 Amazon & E-Commerce",
quickGlobal: "🌍 Globale SEO Tools",

whyTitle: "Warum unsere Tools?",
whyDesc: "90+ professionelle SEO-Tools für Unternehmen weltweit.",

catGlobal: "🌍 Global Universal",
catGlobalDesc: "35+ Tools. Meta-Tags, Plagiat, QR-Codes, Backlinks.",
catPro: "🚀 Advanced Pro",
catProDesc: "18+ professionelle Tools. SERP, CWV, Content Gap.",
catPlatform: "🛒 Plattform-Tools",
catPlatformDesc: "Amazon SEO, FBA-Rechner, E-Commerce.",
catIndia: "🇮🇳 Indien Spezial",
catIndiaDesc: "GST, UPI, PAN, Aadhaar, Udyam, Hinglish SEO.",

searchPlaceholder: "90+ Tools durchsuchen...",
noToolsFound: "Keine Tools gefunden",
tryDifferent: "Andere Keywords versuchen",

indiaBadge: "🇮🇳 Indien Spezial",
indiaTitle: "Tools für Indien",
indiaDesc: "GST-Rechner, UPI QR, PAN, Aadhaar, Udyam, Hinglish SEO.",
viewAllIndia: "Alle 18+ Indien Tools →",

platformBadge: "🛒 Plattform-Tools",
platformTitle: "Amazon & E-Commerce SEO",
platformDesc: "Amazon SEO, FBA-Rechner, Produktrecherche.",
viewAllPlatform: "Alle 10+ Plattform-Tools →",

globalBadge: "🌍 Globale SEO",
globalTitle: "Globale SEO-Tools",
globalDesc: "Für Webmaster weltweit. Meta-Tags, Plagiat, Backlink-Analyse.",
viewAllGlobal: "Alle 35+ Globalen Tools →",

upiTitle: "UPI QR-Generator",
upiDesc: "UPI QR-Codes für GPay, PhonePe, Paytm.",
upiBtn: "UPI QR generieren",
gstTitle: "GST-Rechner",
gstDesc: "CGST, SGST, IGST sofort berechnen.",
gstBtn: "GST berechnen",
hinglishTitle: "Hinglish Konverter",
hinglishDesc: "Hinglish zu englischen Keywords.",
hinglishBtn: "Hinglish konvertieren",
udyamTitle: "Udyam-Checker",
udyamDesc: "Udyam-Registrierung überprüfen.",
udyamBtn: "Udyam prüfen",
panTitle: "PAN-Validator",
panDesc: "PAN-Kartenformat validieren.",
panBtn: "PAN validieren",
aadhaarTitle: "Aadhaar-Maskierung",
aadhaarDesc: "Aadhaar-Nummer sicher maskieren.",
aadhaarBtn: "Aadhaar maskieren",
socialTitle: "Social Media Optimierer",
socialDesc: "Posts für Facebook, Instagram, Twitter optimieren.",
socialBtn: "Posts optimieren",
bhashiniTitle: "Bhashini SEO",
bhashiniDesc: "12+ indische Sprachen SEO.",
bhashiniBtn: "Bhashini SEO",
voiceSearchTitle: "Voice Search Optimierer",
voiceSearchDesc: "Inhalte für Google Voice, Alexa & Siri optimieren.",
voiceSearchBtn: "Voice optimieren",

amazonSeoTitle: "Amazon SEO Tool",
amazonSeoDesc: "Komplette Amazon-Optimierung.",
amazonSeoBtn: "Amazon optimieren",
fbaTitle: "Amazon FBA-Rechner",
fbaDesc: "FBA-Gebühren & Gewinnmargen berechnen.",
fbaBtn: "FBA berechnen",
ecomTitle: "E-Commerce SEO Tool",
ecomDesc: "Shopify, WooCommerce Stores optimieren.",
ecomBtn: "E-Commerce SEO",
priceTitle: "Preisvergleichs-Tool",
priceDesc: "Preise auf Amazon vergleichen.",
priceBtn: "Preise vergleichen",

metaTitle: "Meta-Tag Generator",
metaDesc: "SEO Meta-Tags & Open Graph generieren.",
plagiarismTitle: "Plagiatsprüfung",
plagiarismDesc: "Inhaltsoriginalität prüfen.",
qrTitle: "QR-Code Generator",
qrDesc: "QR-Codes für URLs, Text, WiFi erstellen.",
daTitle: "Domain Authority Checker",
daDesc: "DA/PA-Scores prüfen.",
backlinkTitle: "Backlink Checker",
backlinkDesc: "Backlink-Profil analysieren.",

ctaTitle: "Alle 90+ Tools erkunden",
ctaDesc: "4 Kategorien. 90+ Tools. 100% Kostenlos.",
browseAll: "Alle Kategorien →",

footerDesc: "90+ kostenlose SEO-Tools.",
alsoAvailable: "Auch verfügbar in:",
quickLinks: "Quick Links",
globalToolsFooter: "Globale SEO",
indiaToolsFooter: "Indien Tools",
ecomToolsFooter: "E-Commerce",
popularTools: "Beliebte Tools",
copyright: "© 2026 FreeSEOToolHub.com | Alle Rechte vorbehalten",
privacy: "Datenschutz",
madeIn: "🇮🇳 Für die globale SEO-Community | 2026",

allToolsPageTitle: "90+ Kostenlose SEO-Tools 2026",
allToolsHeader: "🚀 Alle 90+ SEO-Tools (2026)",
allToolsHeaderDesc: "90+ Tools in 4 Kategorien.",
allToolsSearchPlaceholder: "90+ Tools durchsuchen...",

filterAll: "📋 Alle Tools (90+)",
filterGlobal: "🌍 Internationale SEO (42)",
filterPro: "🚀 Professionelle SEO (18)",
filterHot: "🔥 Trending 2026",

globalCatTitle: "Globale Tools",
globalCatDesc: "Für Nutzer weltweit.",
proBadge: "🚀 Profi SEO Tools",
proCatTitle: "Fortgeschrittene Tools",
proCatDesc: "Für SEO-Profis & Agenturen.",

metaTagTitle: "Meta-Tag Generator",
metaTagDesc: "SEO Meta-Tags generieren. 2026 Update.",
generateTags: "Tags generieren",
checkNow: "Jetzt prüfen",
generateQR: "QR generieren",
checkDA: "DA prüfen",
checkBacklinks: "Backlinks prüfen",
findBrokenLinks: "Defekte Links finden",
compressImages: "Bilder komprimieren",
checkSSL: "SSL prüfen",
encodeURL: "URL encodieren",
checkDomain: "Domain prüfen",
generateSchema: "Schema generieren",
checkGrammar: "Grammatik prüfen",
paraphrase: "Umformulieren",
analyzeHeadline: "Überschrift analysieren",
checkDensity: "Dichte prüfen",
testSpeed: "Geschwindigkeit testen",
generateSitemap: "Sitemap generieren",
checkRedirects: "Weiterleitungen prüfen",
checkScore: "Score prüfen",
generateAltText: "Alt-Text generieren",
checkCanonical: "Canonical prüfen",
generateHreflang: "Hreflang generieren",
testResponsive: "Responsive testen",
sortCSV: "CSV sortieren",
validate: "Validieren",
testSchema: "Schema testen",
generateHashtags: "Hashtags generieren",

serpFeatureTitle: "SERP Feature Checker",
serpFeatureDesc: "SERP-Features analysieren.",
checkSERP: "SERP prüfen",
contentGapTitle: "Content Gap Analyzer",
contentGapDesc: "Content-Lücken finden.",
findGaps: "Lücken finden",
cwvTitle: "Core Web Vitals Monitor",
cwvDesc: "LCP, INP, CLS tracken.",
monitorCWV: "CWV überwachen",
inpTitle: "INP Monitor",
inpDesc: "Interaction to Next Paint Monitoring.",
trackINP: "INP tracken",
trafficAnalyzerTitle: "Traffic Analyzer",
trafficAnalyzerDesc: "Website-Traffic analysieren.",
analyzeTraffic: "Traffic analysieren",
competitorSerpTitle: "Competitor SERP Analyzer",
competitorSerpDesc: "Top 10 Ranking-Seiten analysieren.",
analyzeCompetitors: "Konkurrenten analysieren",
gscVisualizerTitle: "GSC Data Visualizer",
gscVisualizerDesc: "Google Search Console Daten visualisieren.",
visualizeGSC: "GSC visualisieren",
keywordDifficultyTitle: "Keyword Difficulty Checker",
keywordDifficultyDesc: "Ranking-Schwierigkeit prüfen.",
checkDifficulty: "Schwierigkeit prüfen",
keywordGapTitle: "Keyword Gap Analyzer",
keywordGapDesc: "Keywords mit Konkurrenten vergleichen.",
compareKeywords: "Keywords vergleichen",
serpFeaturesTitle: "SERP Features Analyzer",
serpFeaturesDesc: "Detaillierte SERP-Analyse.",
analyzeSERP: "SERP analysieren",
serpVolatilityTitle: "SERP Volatility Checker",
serpVolatilityDesc: "SERP-Änderungen tracken.",
checkVolatility: "Volatilität prüfen",
logAnalyzerTitle: "Log Analyzer",
logAnalyzerDesc: "Server-Logs analysieren.",
analyzeLogs: "Logs analysieren",
internalLinkTitle: "Internal Link Suggester",
internalLinkDesc: "Intelligente interne Verlinkung.",
getSuggestions: "Vorschläge erhalten",
sovTitle: "Share of Voice Calculator",
sovDesc: "Marken-Sichtbarkeit berechnen.",
calculateSOV: "SOV berechnen",
marketSaturationTitle: "Market Saturation Checker",
marketSaturationDesc: "Marktsättigung prüfen.",
checkMarket: "Markt prüfen",
mobileDesktopTitle: "Mobile Desktop Rank Tracker",
mobileDesktopDesc: "Mobile vs Desktop Rankings.",
trackRanks: "Ranks tracken",
totalCountBadge: "90+ Tools | 4 Kategorien | 100% Kostenlos | 2026",
madeFor: "🇮🇳 Für die globale SEO-Community | 2026"
},

es: {
brand: "Herramientas SEO Gratis Hub",
home: "Inicio",
allTools: "Todas",
about: "Acerca de",
contact: "Contacto",
blog: "Blog",
language: "Idioma",
chooseLang: "🌐 Elige tu idioma",

heroHighlight: "SEO Gratis",
heroTools: "Herramientas",
heroSubtitle: "Para usuarios globales 🌍",
heroDesc: "90+ herramientas SEO gratis. Meta tags, plagio, QR, backlinks. 100% gratis, sin registro.",
exploreAll: "Explorar 90+ Herramientas",
browseCat: "Ver Categorías",

quickIndia: "🇮🇳 Herramientas India",
quickEcom: "🛒 Amazon y E-Commerce",
quickGlobal: "🌍 SEO Global",

whyTitle: "¿Por qué elegirnos?",
whyDesc: "90+ herramientas SEO profesionales para negocios globales.",

catGlobal: "🌍 Global Universal",
catGlobalDesc: "35+ herramientas. Meta tags, plagio, QR, backlinks.",
catPro: "🚀 Pro Avanzado",
catProDesc: "18+ herramientas. SERP, CWV, content gap.",
catPlatform: "🛒 Plataformas",
catPlatformDesc: "Amazon SEO, FBA, e-commerce.",
catIndia: "🇮🇳 India Especial",
catIndiaDesc: "GST, UPI, PAN, Aadhaar, Hinglish SEO.",

searchPlaceholder: "Buscar 90+ herramientas...",
noToolsFound: "Sin resultados",
tryDifferent: "Prueba otras palabras",

indiaBadge: "🇮🇳 India Especial",
indiaTitle: "Herramientas para India",
indiaDesc: "GST, UPI QR, PAN, Aadhaar, Udyam, Hinglish SEO.",
viewAllIndia: "Ver 18+ Herramientas India →",

platformBadge: "🛒 Plataformas",
platformTitle: "Amazon y E-Commerce SEO",
platformDesc: "Amazon SEO, calculadora FBA, investigación de productos.",
viewAllPlatform: "Ver 10+ Herramientas →",

globalBadge: "🌍 SEO Global",
globalTitle: "SEO Global Esencial",
globalDesc: "Para webmasters mundiales. Meta tags, plagio, backlinks.",
viewAllGlobal: "Ver 35+ Herramientas Globales →",

upiTitle: "Generador UPI QR",
upiDesc: "Códigos QR UPI para GPay, PhonePe, Paytm.",
upiBtn: "Generar UPI QR",
gstTitle: "Calculadora GST",
gstDesc: "Calcular CGST, SGST, IGST.",
gstBtn: "Calcular GST",
hinglishTitle: "Conversor Hinglish",
hinglishDesc: "Convertir Hinglish a palabras clave en inglés.",
hinglishBtn: "Convertir Hinglish",
udyamTitle: "Verificador Udyam",
udyamDesc: "Verificar registro Udyam.",
udyamBtn: "Verificar Udyam",
panTitle: "Validador PAN",
panDesc: "Validar formato de tarjeta PAN.",
panBtn: "Validar PAN",
aadhaarTitle: "Enmascarar Aadhaar",
aadhaarDesc: "Enmascarar número Aadhaar.",
aadhaarBtn: "Enmascarar Aadhaar",
socialTitle: "Optimizador Social",
socialDesc: "Optimizar posts para redes sociales.",
socialBtn: "Optimizar Posts",
bhashiniTitle: "Bhashini SEO",
bhashiniDesc: "SEO en 12+ idiomas indios.",
bhashiniBtn: "Bhashini SEO",
voiceSearchTitle: "Optimizador de Voz",
voiceSearchDesc: "Optimizar para Google Voice, Alexa y Siri.",
voiceSearchBtn: "Optimizar Voz",

amazonSeoTitle: "Herramienta Amazon SEO",
amazonSeoDesc: "Optimización completa de Amazon.",
amazonSeoBtn: "Optimizar Amazon",
fbaTitle: "Calculadora Amazon FBA",
fbaDesc: "Calcular tarifas FBA y márgenes.",
fbaBtn: "Calcular FBA",
ecomTitle: "SEO E-Commerce",
ecomDesc: "Optimizar tiendas Shopify, WooCommerce.",
ecomBtn: "SEO E-Commerce",
priceTitle: "Comparador de Precios",
priceDesc: "Comparar precios en Amazon.",
priceBtn: "Comparar Precios",

metaTitle: "Generador Meta Tags",
metaDesc: "Generar meta tags SEO y Open Graph.",
plagiarismTitle: "Detector de Plagio",
plagiarismDesc: "Verificar originalidad del contenido.",
qrTitle: "Generador QR",
qrDesc: "Crear códigos QR para URLs, texto, WiFi.",
daTitle: "Verificador DA",
daDesc: "Verificar puntuaciones DA/PA.",
backlinkTitle: "Verificador Backlinks",
backlinkDesc: "Analizar perfil de backlinks.",

ctaTitle: "Explorar 90+ Herramientas SEO",
ctaDesc: "4 Categorías. 90+ Herramientas. 100% Gratis.",
browseAll: "Ver Categorías →",

footerDesc: "90+ herramientas SEO gratis.",
alsoAvailable: "También disponible en:",
quickLinks: "Enlaces",
globalToolsFooter: "SEO Global",
indiaToolsFooter: "Herramientas India",
ecomToolsFooter: "E-Commerce",
popularTools: "Populares",
copyright: "© 2026 FreeSEOToolHub.com | Todos los derechos reservados",
privacy: "Privacidad",
madeIn: "🇮🇳 Para la comunidad SEO global | 2026",

allToolsPageTitle: "90+ Herramientas SEO Gratis 2026",
allToolsHeader: "🚀 Todas las 90+ Herramientas (2026)",
allToolsHeaderDesc: "90+ herramientas en 4 categorías.",
allToolsSearchPlaceholder: "Buscar 90+ herramientas...",

filterAll: "📋 Todas (90+)",
filterGlobal: "🌍 SEO Internacional (42)",
filterPro: "🚀 SEO Profesional (18)",
filterHot: "🔥 Tendencia 2026",

globalCatTitle: "Herramientas Globales",
globalCatDesc: "Para usuarios de todo el mundo.",
proBadge: "🚀 Herramientas Pro",
proCatTitle: "Herramientas Avanzadas",
proCatDesc: "Para profesionales SEO.",

metaTagTitle: "Generador Meta Tags",
metaTagDesc: "Generar meta tags SEO. 2026.",
generateTags: "Generar Tags",
checkNow: "Verificar",
generateQR: "Generar QR",
checkDA: "Verificar DA",
checkBacklinks: "Verificar Backlinks",
findBrokenLinks: "Buscar Enlaces Rotos",
compressImages: "Comprimir Imágenes",
checkSSL: "Verificar SSL",
encodeURL: "Codificar URL",
checkDomain: "Verificar Dominio",
generateSchema: "Generar Schema",
checkGrammar: "Verificar Gramática",
paraphrase: "Parafrasear",
analyzeHeadline: "Analizar Titular",
checkDensity: "Verificar Densidad",
testSpeed: "Probar Velocidad",
generateSitemap: "Generar Sitemap",
checkRedirects: "Verificar Redirecciones",
checkScore: "Verificar Puntuación",
generateAltText: "Generar Alt Text",
checkCanonical: "Verificar Canonical",
generateHreflang: "Generar Hreflang",
testResponsive: "Probar Responsive",
sortCSV: "Ordenar CSV",
validate: "Validar",
testSchema: "Probar Schema",
generateHashtags: "Generar Hashtags",

serpFeatureTitle: "Verificador SERP",
serpFeatureDesc: "Analizar características SERP.",
checkSERP: "Verificar SERP",
contentGapTitle: "Analizador de Brechas",
contentGapDesc: "Encontrar brechas de contenido.",
findGaps: "Buscar Brechas",
cwvTitle: "Monitor Core Web Vitals",
cwvDesc: "Rastrear LCP, INP, CLS.",
monitorCWV: "Monitorear CWV",
inpTitle: "Monitor INP",
inpDesc: "Monitoreo de Interaction to Next Paint.",
trackINP: "Rastrear INP",
trafficAnalyzerTitle: "Analizador de Tráfico",
trafficAnalyzerDesc: "Analizar tráfico web.",
analyzeTraffic: "Analizar Tráfico",
competitorSerpTitle: "Analizador SERP Competencia",
competitorSerpDesc: "Analizar páginas top 10.",
analyzeCompetitors: "Analizar Competencia",
gscVisualizerTitle: "Visualizador GSC",
gscVisualizerDesc: "Visualizar datos de Search Console.",
visualizeGSC: "Visualizar GSC",
keywordDifficultyTitle: "Verificador Dificultad",
keywordDifficultyDesc: "Verificar dificultad de ranking.",
checkDifficulty: "Verificar Dificultad",
keywordGapTitle: "Analizador Brecha Keywords",
keywordGapDesc: "Comparar keywords con competencia.",
compareKeywords: "Comparar Keywords",
serpFeaturesTitle: "Analizador SERP",
serpFeaturesDesc: "Análisis detallado SERP.",
analyzeSERP: "Analizar SERP",
serpVolatilityTitle: "Verificador Volatilidad",
serpVolatilityDesc: "Rastrear cambios SERP.",
checkVolatility: "Verificar Volatilidad",
logAnalyzerTitle: "Analizador de Logs",
logAnalyzerDesc: "Analizar logs del servidor.",
analyzeLogs: "Analizar Logs",
internalLinkTitle: "Sugeridor Links Internos",
internalLinkDesc: "Sugerencias de enlaces internos.",
getSuggestions: "Obtener Sugerencias",
sovTitle: "Calculadora Share of Voice",
sovDesc: "Calcular visibilidad de marca.",
calculateSOV: "Calcular SOV",
marketSaturationTitle: "Verificador Saturación",
marketSaturationDesc: "Verificar saturación de mercado.",
checkMarket: "Verificar Mercado",
mobileDesktopTitle: "Tracker Mobile Desktop",
mobileDesktopDesc: "Comparar rankings mobile vs desktop.",
trackRanks: "Rastrear Ranks",
totalCountBadge: "90+ Herramientas | 4 Categorías | 100% Gratis | 2026",
madeFor: "🇮🇳 Para la comunidad SEO global | 2026"
},

en: {
// Navbar
brand: "Free SEO Tools Hub",
home: "Home",
allTools: "All Tools",
about: "About",
contact: "Contact",
blog: "Blog",
language: "Language",
chooseLang: "🌐 Choose Your Language",

// Hero Section
heroHighlight: "Free SEO",
heroTools: "Tools",
heroSubtitle: "For India 🇮🇳 & Global Users 🌍",
heroDesc: "90+ free SEO tools for Indian businesses, e-commerce sellers, and global SEO professionals. GST Calculator, UPI QR Generator, Hinglish SEO, Amazon FBA Calculator, Meta Tags, Plagiarism Checker, and professional SEO tools. All tools 100% free, no signup required, updated for 2026.",
exploreAll: "Explore All 90+ Tools",
browseCat: "Browse Categories",

// Quick Links
quickIndia: "🇮🇳 India Tools",
quickEcom: "🛒 Amazon & E-Commerce",
quickGlobal: "🌍 Global SEO Tools",

// Why Choose
whyTitle: "Why Choose Our Tools?",
whyDesc: "We provide 90+ professional SEO tools designed for Indian businesses, e-commerce sellers, and global users. Every tool is 100% free and can be used instantly without any registration.",

// Categories
catGlobal: "🌍 Global Universal",
catGlobalDesc: "35+ tools for worldwide users. Meta tags, plagiarism, QR codes, backlinks & more.",
catPro: "🚀 Advanced Pro",
catProDesc: "18+ professional tools. SERP analysis, CWV monitoring, content gap & log analysis.",
catPlatform: "🛒 Platform Tools",
catPlatformDesc: "Amazon SEO, FBA calculator, e-commerce & product research tools for sellers.",
catIndia: "🇮🇳 India Specific",
catIndiaDesc: "GST, UPI, PAN, Aadhaar, Udyam, Hinglish & 12+ Indian language SEO tools.",

// Search
searchPlaceholder: "🔍 Search 90+ tools... (GST, UPI, Amazon, QR, Aadhaar, Hinglish)...",
noToolsFound: "No Tools Found",
tryDifferent: "Try different keywords or browse by category below",

// India Special
indiaBadge: "🇮🇳 India Special",
indiaTitle: "Tools for Indian Users",
indiaDesc: "For Indian Businesses & Users: GST Calculator, UPI QR Generator, PAN Validator, Udyam Checker, Aadhaar Mask, Hinglish SEO, and 12+ Indian language tools. Serving India's 500M+ internet users.",
viewAllIndia: "View All 18+ India Tools →",

// Platform Tools
platformBadge: "🛒 Platform Tools",
platformTitle: "Amazon & E-Commerce SEO",
platformDesc: "For Sellers & E-commerce: Amazon SEO tools, FBA calculators, product research, and e-commerce optimization. Amazon sellers worldwide benefit from these free tools.",
viewAllPlatform: "View All 10+ Platform Tools →",

// Global SEO
globalBadge: "🌍 Global SEO",
globalTitle: "Essential Global SEO Tools",
globalDesc: "For Webmasters & SEOs Worldwide: Professional SEO tools that work universally. Meta tags, plagiarism checking, backlink analysis, and more. Used by bloggers, agencies, and businesses globally.",
viewAllGlobal: "View All 35+ Global SEO Tools →",

// Tool Cards - India
upiTitle: "UPI QR Generator",
upiDesc: "Generate UPI payment QR codes for GPay, PhonePe, Paytm.",
upiBtn: "Generate UPI QR",
gstTitle: "GST Calculator",
gstDesc: "Calculate CGST, SGST, IGST instantly. GST invoice ready.",
gstBtn: "Calculate GST",
hinglishTitle: "Hinglish Converter",
hinglishDesc: "Convert Hinglish to English keywords. Voice search ready.",
hinglishBtn: "Convert Hinglish",
udyamTitle: "Udyam Checker",
udyamDesc: "Verify Udyam Registration. MSME business check.",
udyamBtn: "Check Udyam",
panTitle: "PAN Validator",
panDesc: "Validate PAN card format. Tax compliance tool.",
panBtn: "Validate PAN",
aadhaarTitle: "Aadhaar Mask Tool",
aadhaarDesc: "Mask Aadhaar number securely. Show last 4 digits only.",
aadhaarBtn: "Mask Aadhaar",
socialTitle: "Social Media Optimizer",
socialDesc: "Optimize posts for Facebook, Instagram, Twitter & more.",
socialBtn: "Optimize Posts",
bhashiniTitle: "Bhashini SEO",
bhashiniDesc: "12+ Indian languages SEO. Hindi, Tamil, Telugu & more.",
bhashiniBtn: "Bhashini SEO",
voiceSearchTitle: "Voice Search Optimizer",
voiceSearchDesc: "Optimize content for Google Voice, Alexa & Siri. Voice search ready.",
voiceSearchBtn: "Optimize Voice",

// Tool Cards - E-Commerce
amazonSeoTitle: "Amazon SEO Tool Free",
amazonSeoDesc: "Complete Amazon optimization suite with live data API.",
amazonSeoBtn: "Optimize Amazon",
fbaTitle: "Amazon FBA Calculator",
fbaDesc: "Calculate Amazon FBA fees & profit margins instantly.",
fbaBtn: "Calculate FBA",
ecomTitle: "E-Commerce SEO Tool",
ecomDesc: "Optimize Shopify, WooCommerce & Magento stores.",
ecomBtn: "E-Commerce SEO",
priceTitle: "Price Comparison Tool",
priceDesc: "Compare prices across Amazon & e-commerce platforms.",
priceBtn: "Compare Prices",

// Tool Cards - Global
metaTitle: "Meta Tag Generator",
metaDesc: "Generate SEO meta tags, Open Graph & Twitter Cards. 50K+ monthly searches.",
plagiarismTitle: "Plagiarism Checker",
plagiarismDesc: "Check content originality. 80K+ monthly searches. Essential for writers & students worldwide.",
qrTitle: "QR Code Generator",
qrDesc: "Create custom QR codes for URLs, text, WiFi, vCards & more.",
daTitle: "Domain Authority Checker",
daDesc: "Check DA/PA scores. Moz-based domain strength analysis. Compare with competitors.",
backlinkTitle: "Backlink Checker",
backlinkDesc: "Analyze backlink profile. Find who's linking to any website. Competitor research tool.",

// CTA
ctaTitle: "🚀 Ready to Explore All 90+ Free SEO Tools?",
ctaDesc: "4 Categories. 90+ Tools. 100% Free. No Signup Required. Updated 2026.",
browseAll: "Browse All Categories",

// Footer
footerDesc: "90+ free SEO tools for Indian users, Amazon & E-Commerce SEO, and global SEO professionals. 100% free since 2024. Updated for 2026.",
alsoAvailable: "Also available in:",
quickLinks: "Quick Links",
globalToolsFooter: "Global SEO",
indiaToolsFooter: "India Tools",
ecomToolsFooter: "E-Commerce",
popularTools: "Popular Tools",
copyright: "© 2026 FreeSEOToolHub.com | All Rights Reserved",
privacy: "Privacy Policy",
madeIn: "🇮🇳 Made for Indian & Global SEO Community | Updated May 2026",

// All Tools Page
allToolsPageTitle: "90+ Free SEO Tools 2026 | All Categories | FreeSEOToolHub",
allToolsHeader: "🚀 All 90+ Free SEO Tools (2026)",
allToolsHeaderDesc: "Complete collection of 90+ free SEO tools in 4 categories. India Special, Amazon & E-Commerce, International SEO, and Professional SEO Tools. All tools 100% free, no signup required.",
allToolsSearchPlaceholder: "🔍 Search all 90+ tools... (GST, UPI, Amazon, QR, meta tags, plagiarism, backlink, SERP, keywords)...",

filterAll: "📋 All Tools (90+)",
filterGlobal: "🌍 International SEO (42)",
filterPro: "🚀 Professional SEO (18)",
filterHot: "🔥 Trending 2026",

globalCatTitle: "Global Tools - No Regional Limits",
globalCatDesc: "For Worldwide Users: These global SEO tools work universally — no regional restrictions. Perfect for bloggers, webmasters, developers, and SEO professionals across US, UK, Europe, and globally.",
proBadge: "🚀 Professional SEO Tools",
proCatTitle: "Advanced Tools for Experts",
proCatDesc: "For SEO Professionals & Agencies: Advanced professional SEO tools for competitor analysis, SERP tracking, Core Web Vitals monitoring, INP tracking, and content gap analysis.",

metaTagTitle: "Meta Tag Generator",
metaTagDesc: "Generate SEO meta tags, Open Graph & Twitter Cards. Updated 2026.",
generateTags: "Generate Tags",
checkNow: "Check Now",
generateQR: "Generate QR",
checkDA: "Check DA",
checkBacklinks: "Check Backlinks",
findBrokenLinks: "Find Broken Links",
compressImages: "Compress Images",
checkSSL: "Check SSL",
encodeURL: "Encode URL",
checkDomain: "Check Domain",
generateSchema: "Generate Schema",
checkGrammar: "Check Grammar",
paraphrase: "Paraphrase",
analyzeHeadline: "Analyze Headline",
checkDensity: "Check Density",
testSpeed: "Test Speed",
generateSitemap: "Generate Sitemap",
checkRedirects: "Check Redirects",
checkScore: "Check Score",
generateAltText: "Generate Alt Text",
checkCanonical: "Check Canonical",
generateHreflang: "Generate Hreflang",
testResponsive: "Test Responsive",
sortCSV: "Sort CSV",
validate: "Validate",
testSchema: "Test Schema",
generateHashtags: "Generate Hashtags",

serpFeatureTitle: "SERP Feature Checker",
serpFeatureDesc: "Analyze SERP features. Featured snippets, PAA, knowledge panels.",
checkSERP: "Check SERP",
contentGapTitle: "Content Gap Analyzer",
contentGapDesc: "Find content gaps vs competitors. Strategic opportunities.",
findGaps: "Find Gaps",
cwvTitle: "Core Web Vitals Monitor",
cwvDesc: "Track LCP, INP, CLS. Essential for Google ranking.",
monitorCWV: "Monitor CWV",
inpTitle: "INP Monitor",
inpDesc: "Interaction to Next Paint monitoring. New Core Web Vital 2026.",
trackINP: "Track INP",
trafficAnalyzerTitle: "Traffic Analyzer",
trafficAnalyzerDesc: "Analyze website traffic. Competitor traffic estimation.",
analyzeTraffic: "Analyze Traffic",
competitorSerpTitle: "Competitor SERP Analyzer",
competitorSerpDesc: "Analyze top 10 ranking pages. Reverse engineer success.",
analyzeCompetitors: "Analyze Competitors",
gscVisualizerTitle: "GSC Data Visualizer",
gscVisualizerDesc: "Visualize Google Search Console data with interactive charts.",
visualizeGSC: "Visualize GSC",
keywordDifficultyTitle: "Keyword Difficulty Checker",
keywordDifficultyDesc: "Check ranking difficulty. Find easy-to-rank keywords.",
checkDifficulty: "Check Difficulty",
keywordGapTitle: "Keyword Gap Analyzer",
keywordGapDesc: "Compare keywords vs competitors. Find missing keywords.",
compareKeywords: "Compare Keywords",
serpFeaturesTitle: "SERP Features Analyzer",
serpFeaturesDesc: "Detailed SERP feature analysis for any keyword.",
analyzeSERP: "Analyze SERP",
serpVolatilityTitle: "SERP Volatility Checker",
serpVolatilityDesc: "Track SERP changes. Detect Google algorithm updates.",
checkVolatility: "Check Volatility",
logAnalyzerTitle: "Log Analyzer",
logAnalyzerDesc: "Analyze server logs. Understand Googlebot crawl behavior.",
analyzeLogs: "Analyze Logs",
internalLinkTitle: "Internal Link Suggester",
internalLinkDesc: "Smart internal linking suggestions for SEO.",
getSuggestions: "Get Suggestions",
sovTitle: "Share of Voice Calculator",
sovDesc: "Calculate brand visibility vs competitors in search.",
calculateSOV: "Calculate SOV",
marketSaturationTitle: "Market Saturation Checker",
marketSaturationDesc: "Check market saturation for any niche.",
checkMarket: "Check Market",
mobileDesktopTitle: "Mobile Desktop Rank Tracker",
mobileDesktopDesc: "Compare mobile vs desktop rankings.",
trackRanks: "Track Ranks",

brokenLinkTitle: "Broken Link Checker",
brokenLinkDesc: "Find 404 errors and dead links on any website.",
imageCompressTitle: "Image Compressor",
imageCompressDesc: "Compress JPG, PNG, WebP images. Reduce file size, keep quality.",
sslTitle: "SSL Checker",
sslDesc: "Check SSL certificate validity & expiration date.",
urlEncoderTitle: "URL Encoder/Decoder",
urlEncoderDesc: "Encode & decode URLs. Essential developer tool.",
domainCheckTitle: "Domain Checker",
domainCheckDesc: "Check domain availability & registration details.",
schemaTitle: "Schema Markup Generator",
schemaDesc: "Create JSON-LD structured data for rich snippets.",
grammarTitle: "Grammar & Spell Checker",
grammarDesc: "Check grammar, spelling & punctuation errors.",
paraphraseTitle: "Paraphrasing Tool",
paraphraseDesc: "Rewrite content with AI. Avoid plagiarism, improve readability.",
headlineTitle: "Heading Headline Analyzer",
headlineDesc: "Score your headlines. Improve CTR with better titles.",
keywordDensityTitle: "Keyword Density Checker",
keywordDensityDesc: "Analyze keyword density & frequency on any page.",
speedTestTitle: "Website Speed Test",
speedTestDesc: "Test page load time & performance metrics.",
sitemapTitle: "XML Sitemap Generator",
sitemapDesc: "Generate XML sitemaps for better indexing.",
redirectTitle: "Redirect Chain Checker",
redirectDesc: "Find redirect chains & loops. Fix SEO issues.",
readabilityTitle: "Readability Score Checker",
readabilityDesc: "Flesch-Kincaid reading ease. Improve content readability.",
altGeneratorTitle: "Image Alt Generator",
altGeneratorDesc: "Generate SEO-friendly alt texts for images.",
canonicalTitle: "Canonical URL Checker",
canonicalDesc: "Check canonical tags. Prevent duplicate content issues.",
hreflangTitle: "Hreflang Generator",
hreflangDesc: "Generate hreflang tags for multilingual sites.",
responsiveTitle: "Responsive Tester",
responsiveDesc: "Test website on different screen sizes.",
csvSorterTitle: "CSV Sorter",
csvSorterDesc: "Sort, filter & organize CSV files online.",
headingStructureTitle: "Heading Structure Validator",
headingStructureDesc: "Validate H1-H6 heading hierarchy for SEO.",
schemaTesterTitle: "Schema Structured Data Tester",
schemaTesterDesc: "Test & validate schema markup code.",
hashtagTitle: "Hashtag Generator",
hashtagDesc: "Generate trending hashtags for social media.",
totalCountBadge: "90+ Free SEO Tools | 4 Categories | 100% Free | No Signup Required | Updated 2026",
madeFor: "🇮🇳 Made for Global SEO Community | Updated 2026"
}
};

// =============================================
// Language Functions
// =============================================

function getLang() {
const params = new URLSearchParams(window.location.search);
return params.get('lang') || 'en';
}

function applyLanguage(lang) {
const t = translations[lang];
if (!t) return;

// Apply all data-translate elements
document.querySelectorAll('[data-translate]').forEach(el => {
const key = el.getAttribute('data-translate');
if (t[key]) {
if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
el.placeholder = t[key];
} else {
el.textContent = t[key];
}
}
});

// Update HTML lang
document.documentElement.lang = lang;
if (t.brand) document.title = t.brand;

// Save preference
localStorage.setItem('preferredLang', lang);
}

// Language switch function
function switchLanguage(lang) {
const url = new URL(window.location);
url.searchParams.set('lang', lang);
window.location = url.toString();
}

// Page Load
document.addEventListener('DOMContentLoaded', () => {
const savedLang = localStorage.getItem('preferredLang');
const urlLang = new URLSearchParams(window.location.search).get('lang');
const lang = urlLang || savedLang || 'en';
applyLanguage(lang);
});

// Add lang parameter to all internal links
document.addEventListener('DOMContentLoaded', function() {
const lang = getLang();
if (lang !== 'en') {
document.querySelectorAll('a').forEach(link => {
try {
const url = new URL(link.href, window.location.origin);
if (url.hostname === window.location.hostname) {
url.searchParams.set('lang', lang);
link.href = url.pathname + url.search;
}
} catch(e) {}
});
}
});
